name: ✨ Feature request
description: Suggest an idea for this software
labels: [ "enhancement" ]
projects: [ "gy-mate/2" ]
assignees:
  - gy-mate
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What should be improved?
      placeholder: I always get frustrated when...
    validations:
      required: true
  - type: input
    id: app_version
    attributes:
      label: Version
      description: Which version of `kalauz` are you using?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Preferred solution
      description: A clear and concise description of what you want to happen in these cases.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: A clear and concise description of any alternative solutions or features you've considered.
